version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/song-recognition
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      runas: ubuntu
